export const data = [
  {
    brand: "iPhone",
    modelName: "13",
    color: "white",
    os: "ios",
    rate: "20,000",
  },
  {
    brand: "Samsung",
    modelName: "S22 Ultra",
    color: "black",
    os: "android",
    rate: "30,000",
  },
  {
    brand: "Nokia",
    modelName: "c63",
    color: "green",
    os: "symbion",
    rate: "40,000",
  },
  {
    brand: "Nokia",
    modelName: "n80",
    color: "black",
    os: "symbion",
    rate: "50,000",
  },
  {
    brand: "iPhone",
    modelName: "X",
    color: "black",
    os: "ios",
    rate: "10,000",
  },
  {
    brand: "iPhone",
    modelName: "12",
    color: "pink",
    os: "ios",
    rate: "40,000",
  },
  {
    brand: "iPhone",
    modelName: "13",
    color: "gold",
    os: "ios",
    rate: "70,000",
  },
  {
    brand: "Samsung",
    modelName: "S9",
    color: "Smoke Gray",
    os: "android",
    rate: "80,000",
  },
  {
    brand: "Samsung",
    modelName: "S3",
    color: "Smoke Red",
    os: "android",
    rate: "6,000",
  },
  {
    brand: "Nokia",
    modelName: "1503",
    color: "Yellow",
    os: "windows X",
    rate: "60,000",
  },
  {
    brand: "oppo",
    modelName: "n1",
    color: "orange",
    os: "android",
    rate: "20",
  },
];
